### ISSUE TITLE
Array totalMoneySpent stays empty even after pushing elements in the function loadUserStatistics()

### ISSUE THREAD

**Issue by velho-oscar** [velho-oscar/vehicle-expenses#1]
In the `main.js` file there's function `loadUserStatistics(user)`.
At the beggining we're initalizing an empty array called `totalMoneySpent` where all expenses' `totalPrice` should be stored. 
Then we call firebase function to get all expenses and we loop through each expense doing some calculations and displaying the expense list. In the `.then()` section we push each `totalPrice` to the array and while debugging it the array is filled up correctly. But after that the data is lost and the array is empty. I need to find a way to preserve the data. I think it's something about `.then()`.

**Comment by Ullauri** [comment]
Code inside `.then` is called after the promise is resolved, which, in this case, can happen after [this line is reached](https://github.com/velho-oscar/vehicle-expenses/blob/master/public/js/main.js#L130).

You can try moving all the code above and below the db call into the `.then` to fix it.

**Comment by velho-oscar** [comment]
> Code inside .then is called after the promise is resolved, which, in this case, can happen after this line is reached. You can try moving all the code above and below the db call into the .then to fix it.

Many thanks, still don't know how to achieve that but will try for sure soon.
